"""Snapshot tests: compare new mesh implementations against PETSc reference data.

Reference .npz files were generated by loading .msh files through the current
PETSc-based Mesh.from_gmsh() and saving all 33 fields.  These tests verify
that the new pure-numpy mesh classes reproduce the same results.
"""

import os
from pathlib import Path

import numpy as np
import pytest

REF_DIR = Path(__file__).parent / "mesh_references"

MESH_CASES = ["square_quad", "triangle", "tetra3d", "channel_hole"]


def _load_ref(name):
    path = REF_DIR / f"ref_{name}.npz"
    if not path.exists():
        pytest.skip(f"Reference file not found: {path}")
    return dict(np.load(str(path), allow_pickle=True))


# ---------------------------------------------------------------------------
# Geometry field names that should match PETSc within tolerance
# ---------------------------------------------------------------------------
GEOMETRY_FIELDS = [
    "cell_centers",
    "cell_volumes",
    "cell_inradius",
    "face_normals",
    "face_volumes",
    "face_centers",
    "face_subvolumes",
]

TOPOLOGY_FIELDS = [
    "vertex_coordinates",
    "cell_vertices",
    "cell_faces",
    "face_cells",
    "cell_neighbors",
]

BOUNDARY_FIELDS = [
    "boundary_face_cells",
    "boundary_face_ghosts",
    "boundary_face_function_numbers",
    "boundary_face_physical_tags",
    "boundary_face_face_indices",
    "boundary_conditions_sorted_physical_tags",
]

SCALAR_FIELDS = [
    "dimension",
    "n_cells",
    "n_inner_cells",
    "n_faces",
    "n_vertices",
    "n_boundary_faces",
    "n_faces_per_cell",
]

LSQ_FIELDS = [
    "lsq_gradQ",
    "lsq_neighbors",
    "lsq_scale_factors",
]


# ---------------------------------------------------------------------------
# Reference data sanity checks (ensure the snapshots are loadable)
# ---------------------------------------------------------------------------
class TestReferenceDataLoads:
    @pytest.mark.parametrize("case", MESH_CASES)
    def test_ref_has_all_fields(self, case):
        ref = _load_ref(case)
        for field in SCALAR_FIELDS + TOPOLOGY_FIELDS + GEOMETRY_FIELDS + BOUNDARY_FIELDS + LSQ_FIELDS:
            assert field in ref, f"Missing field '{field}' in ref_{case}.npz"

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_ref_scalars_sensible(self, case):
        ref = _load_ref(case)
        assert int(ref["dimension"]) in (1, 2, 3)
        assert int(ref["n_inner_cells"]) > 0
        assert int(ref["n_faces"]) > 0
        assert int(ref["n_vertices"]) > 0
        assert int(ref["n_cells"]) >= int(ref["n_inner_cells"])

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_ref_volumes_positive(self, case):
        ref = _load_ref(case)
        n_inner = int(ref["n_inner_cells"])
        assert np.all(ref["cell_volumes"][:n_inner] > 0)
        assert np.all(ref["face_volumes"] > 0)

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_ref_normals_unit(self, case):
        ref = _load_ref(case)
        dim = int(ref["dimension"])
        normals = ref["face_normals"][:dim, :]
        norms = np.linalg.norm(normals, axis=0)
        np.testing.assert_allclose(norms, 1.0, atol=1e-12)


# ---------------------------------------------------------------------------
# PETSc vs numpy geometry comparison (run only if PETSc available)
# ---------------------------------------------------------------------------
_HAVE_PETSC = False  # PETSc Mesh class removed; keep flag for skip guards


@pytest.mark.skipif(not _HAVE_PETSC, reason="PETSc not available")
class TestGeometryVsPetsc:
    """Load the same .msh with PETSc, then compare geometry against reference."""

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_cell_volumes_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        m = PetscMesh.from_gmsh(str(msh_path))
        np.testing.assert_allclose(m.cell_volumes, ref["cell_volumes"], atol=1e-12)

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_cell_centers_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        m = PetscMesh.from_gmsh(str(msh_path))
        np.testing.assert_allclose(m.cell_centers, ref["cell_centers"], atol=1e-12)

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_face_normals_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        m = PetscMesh.from_gmsh(str(msh_path))
        np.testing.assert_allclose(m.face_normals, ref["face_normals"], atol=1e-12)

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_face_volumes_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        m = PetscMesh.from_gmsh(str(msh_path))
        np.testing.assert_allclose(m.face_volumes, ref["face_volumes"], atol=1e-12)

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_cell_inradius_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        m = PetscMesh.from_gmsh(str(msh_path))
        np.testing.assert_allclose(m.cell_inradius, ref["cell_inradius"], atol=1e-12)


# ---------------------------------------------------------------------------
# LSQ gradient accuracy on polynomial test functions
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _HAVE_PETSC, reason="PETSc not available")
class TestLSQGradientAccuracy:
    """Verify LSQ gradient reconstruction on polynomial test functions."""

    def _load_mesh(self, case):
        msh_path = REF_DIR / f"test_{case}.msh"
        if not msh_path.exists():
            pytest.skip(f"MSH file not found: {msh_path}")
        return PetscMesh.from_gmsh(str(msh_path))

    @pytest.mark.parametrize("case", ["square_quad", "triangle", "channel_hole"])
    def test_linear_gradient_2d(self, case):
        """For u(x,y) = 2x + 3y, gradient should be [2, 3] everywhere."""
        from zoomy_core.mesh.lsq_reconstruction import compute_derivatives

        m = self._load_mesh(case)
        dim = m.dimension
        centers = m.cell_centers[:dim, :].T  # (n_cells, dim)
        u = 2 * centers[:, 0] + 3 * centers[:, 1]

        grad = compute_derivatives(u, m, derivatives_multi_index=[(1, 0), (0, 1)])
        n_inner = m.n_inner_cells

        np.testing.assert_allclose(grad[:n_inner, 0], 2.0, atol=1e-5)
        np.testing.assert_allclose(grad[:n_inner, 1], 3.0, atol=1e-5)

    def test_linear_gradient_3d(self):
        """For u(x,y,z) = x + 2y + 3z, gradient should be [1, 2, 3]."""
        from zoomy_core.mesh.lsq_reconstruction import compute_derivatives

        m = self._load_mesh("tetra3d")
        dim = m.dimension
        centers = m.cell_centers[:dim, :].T
        u = centers[:, 0] + 2 * centers[:, 1] + 3 * centers[:, 2]

        grad = compute_derivatives(
            u, m, derivatives_multi_index=[(1, 0, 0), (0, 1, 0), (0, 0, 1)]
        )
        n_inner = m.n_inner_cells

        np.testing.assert_allclose(grad[:n_inner, 0], 1.0, atol=1e-6)
        np.testing.assert_allclose(grad[:n_inner, 1], 2.0, atol=1e-6)
        np.testing.assert_allclose(grad[:n_inner, 2], 3.0, atol=1e-6)


# ---------------------------------------------------------------------------
# New mesh hierarchy tests against PETSc references
# ---------------------------------------------------------------------------
from zoomy_core.mesh.base_mesh import BaseMesh
from zoomy_core.mesh.fvm_mesh import FVMMesh
from zoomy_core.mesh.subvolume_mesh import SubVolumeMesh
from zoomy_core.mesh.lsq_mesh import LSQMesh


class TestBaseMeshFromMsh:
    """BaseMesh.from_msh() topology should match PETSc reference."""

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_counts_match(self, case):
        ref = _load_ref(case)
        msh_path = REF_DIR / f"test_{case}.msh"
        m = BaseMesh.from_msh(str(msh_path))
        assert m.n_inner_cells == int(ref["n_inner_cells"])
        assert m.n_faces == int(ref["n_faces"])
        assert m.n_vertices == int(ref["n_vertices"])
        assert m.n_cells == int(ref["n_cells"])
        assert m.n_boundary_faces == int(ref["n_boundary_faces"])

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_h5_roundtrip(self, case, tmp_path):
        msh_path = REF_DIR / f"test_{case}.msh"
        m = BaseMesh.from_msh(str(msh_path))
        h5_path = str(tmp_path / f"{case}.h5")
        m.write_to_hdf5(h5_path)
        m2 = BaseMesh.from_hdf5(h5_path)
        assert m2.n_cells == m.n_cells
        assert m2.n_faces == m.n_faces
        np.testing.assert_array_equal(m2.cell_vertices, m.cell_vertices)
        np.testing.assert_array_equal(m2.face_cells, m.face_cells)


class TestFVMMeshGeometry:
    """FVMMesh geometry should match PETSc reference within tolerance."""

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_cell_volumes_match(self, case):
        ref = _load_ref(case)
        m = FVMMesh.from_msh(str(REF_DIR / f"test_{case}.msh"))
        n = m.n_inner_cells
        np.testing.assert_allclose(
            np.sort(m.cell_volumes_computed()[:n]),
            np.sort(ref["cell_volumes"][:n]), atol=1e-14,
        )

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_face_volumes_match(self, case):
        ref = _load_ref(case)
        m = FVMMesh.from_msh(str(REF_DIR / f"test_{case}.msh"))
        np.testing.assert_allclose(
            np.sort(m.face_volumes_computed()),
            np.sort(ref["face_volumes"]), atol=1e-14,
        )

    @pytest.mark.parametrize("case", MESH_CASES)
    def test_cell_inradius_match(self, case):
        ref = _load_ref(case)
        m = FVMMesh.from_msh(str(REF_DIR / f"test_{case}.msh"))
        n = m.n_inner_cells
        np.testing.assert_allclose(
            np.sort(m.cell_inradius_computed()[:n]),
            np.sort(ref["cell_inradius"][:n]), atol=1e-14,
        )


class TestSubVolumeMesh:
    @pytest.mark.parametrize("case", MESH_CASES)
    def test_subvolumes_match(self, case):
        ref = _load_ref(case)
        m = SubVolumeMesh.from_msh(str(REF_DIR / f"test_{case}.msh"))
        np.testing.assert_allclose(
            np.sort(m.face_subvolumes_computed().ravel()),
            np.sort(ref["face_subvolumes"].ravel()), atol=1e-14,
        )


class TestLSQMeshGradient:
    @pytest.mark.parametrize("case", ["square_quad", "triangle", "channel_hole"])
    def test_linear_gradient_2d(self, case):
        m = LSQMesh.from_msh(str(REF_DIR / f"test_{case}.msh"))
        dim = m.dimension
        centers = m.cell_centers_computed()[:dim, :].T
        u = 2 * centers[:, 0] + 3 * centers[:, 1]
        grad = m.compute_derivatives(u, derivatives_multi_index=[(1, 0), (0, 1)])
        n = m.n_inner_cells
        np.testing.assert_allclose(grad[:n, 0], 2.0, atol=1e-5)
        np.testing.assert_allclose(grad[:n, 1], 3.0, atol=1e-5)

    def test_linear_gradient_3d(self):
        m = LSQMesh.from_msh(str(REF_DIR / "test_tetra3d.msh"))
        centers = m.cell_centers_computed()[:3, :].T
        u = centers[:, 0] + 2 * centers[:, 1] + 3 * centers[:, 2]
        grad = m.compute_derivatives(
            u, derivatives_multi_index=[(1, 0, 0), (0, 1, 0), (0, 0, 1)]
        )
        n = m.n_inner_cells
        np.testing.assert_allclose(grad[:n, 0], 1.0, atol=1e-5)
        np.testing.assert_allclose(grad[:n, 1], 2.0, atol=1e-5)
        np.testing.assert_allclose(grad[:n, 2], 3.0, atol=1e-5)

    def test_1d_gradient(self):
        m = LSQMesh.create_1d((0, 1), 20)
        centers = m.cell_centers_computed()[:1, :].T
        u = 5.0 * centers[:, 0]
        grad = m.compute_derivatives(u, derivatives_multi_index=[(1,)])
        n = m.n_inner_cells
        np.testing.assert_allclose(grad[:n, 0], 5.0, atol=1e-5)
