"""Codegen driver for the title-slide background-video app.

The model is the *same* SWE model as the browser game: same flux, same
HLLC numerics, same inflow/outflow/wall BC kernels.  We just re-emit
the kernels into a local ``generated/`` so the page is self-contained
and works whether or not ``apps/swe-game`` is also generated.

Run from the ``zoomy`` conda env::

    python apps/title-slide/generate.py

The Q(t) timeline block is identical to the game's — 20 points spanning
``[0, END_TIME]`` — but the runtime JS engine **remaps the timeline
times** to whatever ``endTime`` the user picks in the UI, so the
default 60 s baseline here is not a hard ceiling.
"""

import importlib.util
import json
import re
from pathlib import Path

from zoomy_core.fvm.riemann_solvers import HLLC
from zoomy_core.transformation.to_glsl import GlslModel, GlslNumerics
from zoomy_core.transformation.to_js import JsModel, JsNumerics


def _import_swe_game():
    """Load apps/swe-game/generate.py without touching sys.path."""
    here = Path(__file__).resolve().parent
    src = here.parent / "swe-game" / "generate.py"
    spec = importlib.util.spec_from_file_location("_swe_game_generate", src)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _exported(code):
    names = sorted(set(re.findall(r"^function (\w+)\(", code, re.M)))
    return code + "\n\nexport { " + ", ".join(names) + " };\n"


def main():
    sg = _import_swe_game()
    model = sg.build_model()
    numerics = HLLC(model)
    out_dir = Path(__file__).parent / "generated"
    out_dir.mkdir(exist_ok=True)

    js_bc, _ = sg.per_tag_bc_kernels(model, JsModel(model))
    js = "\n\n".join([
        "// AUTO-GENERATED by apps/title-slide/generate.py — do not edit.",
        JsModel(model).generate(),
        JsNumerics(numerics).generate(),
        js_bc,
    ])
    (out_dir / "swe2d.js").write_text(_exported(js))

    glsl_bc, _ = sg.per_tag_bc_kernels(model, GlslModel(model))
    glsl = "\n\n".join([
        "// AUTO-GENERATED by apps/title-slide/generate.py — do not edit.",
        GlslModel(model).generate(),
        GlslNumerics(numerics).generate(),
        glsl_bc,
    ])
    (out_dir / "swe2d.glsl").write_text(glsl)

    param_names = list(model._parameter_symbols.keys())
    meta = {
        "nVars": model.n_variables,
        "nAux": model.n_aux_variables,
        "dimension": model.dimension,
        "parameterNames": param_names,
        "parameterDefaults": [float(v) for v in model.parameters.values()],
        "timelineBlock": {
            "nPoints": sg.N_TIMELINE,
            "timeStart": param_names.index("q_t_0"),
            "valueStart": param_names.index("q_v_0"),
        },
        "boundaryTags": list(
            model.boundary_conditions.list_sorted_function_names
        ),
        "numerics": numerics.__class__.__name__,
    }
    (out_dir / "swe2d_meta.json").write_text(json.dumps(meta, indent=2))

    glsl_js = (
        "// AUTO-GENERATED by apps/title-slide/generate.py — do not edit.\n"
        "// GLSL kernels + metadata, exposed as window.SWE2D for the WebGL engine.\n"
        "window.SWE2D = {\n"
        f"  meta: {json.dumps(meta)},\n"
        f"  glsl: {json.dumps(glsl)},\n"
        "};\n"
    )
    (out_dir / "swe2d_glsl.js").write_text(glsl_js)

    print(f"wrote {out_dir}/swe2d.js, swe2d.glsl, swe2d_meta.json, swe2d_glsl.js")
    print(f"  boundary tags: {meta['boundaryTags']}")
    print(f"  parameters: {len(param_names)}")


if __name__ == "__main__":
    main()
